"""
This file is responsible for implementing the tuple class.
This class exposes APIs for creating a tuple.
Every tuple as an autogenerated unique id (unsigned int).
After creating a tuple you get back the byte sequence.
"""
class Tuple:
    TUPLE_MAX_SIZE = 256
    MAX_COL_COUNT = 4

    def __init__(self):
        pass

    def create_tuple(self, *args) -> bytearray:
        byte_array = bytearray(self.TUPLE_MAX_SIZE)
        offset = 0
        for arg in args:
            byte_array[offset : offset + self.TUPLE_MAX_SIZE] = arg
        return byte_array