DATABASE_FILE_PATH = "/Users/deep/personal-projects/toy-db/toydb.db"
ROOT_PAGE_HEADER_SIZE = 100
BTREE_PAGE_HEADER_SIZE = 8
PAGE_SIZE = 4096
TEXT_ENCODING_MAP = {"UTF-8": 1, "UTF-16le": 2}
DATABASE_HEADER_STRUCTURE = {
    "HEADER_STRING": {"OFFSET": 0, "SIZE": 90},
    "PAGE_SIZE": {"OFFSET": 90, "SIZE": 2},
    "TEXT_ENCODING": {"OFFSET": 92, "SIZE": 1},
}
INT32_MAX = 2**31 - 1
SCHEMA_TABLE_ROOT_PAGE_NUMBER = 0
PAGE_TYPE = {0: "ROOT_PAGE", 1: "TABLE_BTREE_PAGE", 2: "INDEX_BTREE_PAGE"}


class PageHeader:
    ROOT_PAGE_OFFSET = 100
    BTREE_PAGE_OFFSET = 0
    BTREE_PAGE_HEADER_SIZE = 8


class PageConstants:
    RECORD_OFFSET = 108
    RECORD_SIZE_BYTES = 200


class PageRecordConstants:
    KEY_OFFSET = 0
    KEY_SIZE_BYTES = 4
    VALUE_OFFSET = 4
    VALUE_SIZE_BYTES = 196
