DATABASE_FILE_PATH = "/Users/deep/personal-projects/toy-db/toydb.db"
ROOT_PAGE_HEADER_SIZE = 100
BTREE_PAGE_HEADER_SIZE = 8
PAGE_SIZE = 4096
TEXT_ENCODING_MAP = {"UTF-8": 1, "UTF-16le": 2}
DATABASE_HEADER_STRUCTURE = {
    "HEADER_STRING": {"OFFSET": 0, "SIZE": 100},
    "PAGE_SIZE": {"OFFSET": 100, "SIZE": 2},
    "TEXT_ENCODING": {"OFFSET": 102, "SIZE": 1},
}
